-- ============================================
-- Customer Shopping Behavior Analysis
-- SQL Queries
-- Author: Shelly Baisla
-- ============================================

-- Database Setup
CREATE DATABASE customer_behaviour;
USE customer_behaviour;

-- Preview Data
SELECT * FROM customer_behaviour LIMIT 10;

-- ============================================
-- 1. Total Revenue by Gender
-- ============================================
-- What is the total revenue generated by male vs. female customers?
SELECT 
    gender,
    SUM(purchase_amount) AS revenue
FROM customer_behaviour
GROUP BY gender;

-- ============================================
-- 2. Discount Users Who Spent Above Average
-- ============================================
-- Which customers used a discount but still spent more than the average purchase amount?
SELECT 
    customer_id,
    purchase_amount
FROM customer_behaviour
WHERE discount_applied = 'Yes' 
AND purchase_amount >= (
    SELECT AVG(purchase_amount) 
    FROM customer_behaviour
);

-- ============================================
-- 3. Top 5 Products by Review Rating
-- ============================================
-- Which are the top 5 products with the highest average review rating?
SELECT 
    item_purchased,
    ROUND(AVG(review_rating), 2) AS avg_product_rating
FROM customer_behaviour
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- ============================================
-- 4. Shipping Type Purchase Comparison
-- ============================================
-- Compare the average purchase amounts between Standard and Express shipping?
SELECT 
    shipping_type,
    ROUND(AVG(purchase_amount), 2) AS avg_purchase_amount
FROM customer_behaviour
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;

-- ============================================
-- 5. Subscriber vs Non-Subscriber Spending
-- ============================================
-- Do subscribed customers spend more?
SELECT 
    subscription_status,
    COUNT(customer_id) AS total_customers,
    ROUND(AVG(purchase_amount), 2) AS avg_spend,
    ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer_behaviour
GROUP BY subscription_status
ORDER BY total_revenue, avg_spend DESC;

-- ============================================
-- 6. Products with Highest Discount Usage
-- ============================================
-- Which 5 products have the highest percentage of purchases with discounts applied?
SELECT 
    item_purchased,
    ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) / COUNT(*), 2) AS discount_rate
FROM customer_behaviour
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- ============================================
-- 7. Customer Segmentation
-- ============================================
-- Segment customers into New, Returning, and Loyal based on previous purchases
WITH customer_type AS (
    SELECT 
        customer_id,
        previous_purchases,
        CASE 
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM customer_behaviour
)
SELECT 
    customer_segment,
    COUNT(*) AS number_of_customers
FROM customer_type
GROUP BY customer_segment;

-- ============================================
-- 8. Top 3 Products per Category
-- ============================================
-- What are the top 3 most purchased products within each category?
WITH item_counts AS (
    SELECT 
        category,
        item_purchased,
        COUNT(customer_id) AS total_orders,
        ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer_behaviour
    GROUP BY category, item_purchased
)
SELECT 
    item_rank,
    category,
    item_purchased,
    total_orders
FROM item_counts
WHERE item_rank <= 3;

-- ============================================
-- 9. Repeat Buyers & Subscription Status
-- ============================================
-- Are customers who are repeat buyers (more than 5 previous purchases) likely to subscribe?
SELECT 
    subscription_status,
    COUNT(customer_id) AS repeat_buyers
FROM customer_behaviour
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- ============================================
-- 10. Revenue by Age Group
-- ============================================
-- What is the revenue contribution of each age group?
SELECT 
    age_group,
    SUM(purchase_amount) AS total_revenue
FROM customer_behaviour
GROUP BY age_group
ORDER BY total_revenue DESC;
